name: Tests and Lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

permissions:
  contents: read  # Required for checking out code and reading coverage files
  actions: write  # Required for saving cache

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install tox and coverage
        run: pip install tox tox-gh-actions build

      - name: Install build dependency
        run: python3 -m pip install --upgrade pip build

      - name: Test Build binary wheel and source tarball
        run: python3 -m build --sdist --wheel --outdir dist/ .

      - name: Restore mypy cache
        id: cache-mypy-restore
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: |
            .mypy_cache
          key: ${{ runner.os }}-py${{ matrix.python-versions }}-mypy-${{ hashFiles('**/.mypy_cache') }}

      - name: Run Python tests
        run: |
          make tests

      - name: Save mypy cache
        id: cache-mypy-save
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: |
            .mypy_cache
          key: ${{ runner.os }}-py${{ matrix.python-versions }}-mypy-${{ hashFiles('**/.mypy_cache') }}

      - name: Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          files: coverage.xml
          fail_ci_if_error: false
          verbose: true
